<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EFCore\EFCore.csproj" />
    <ProjectReference Include="..\ERP.Orchestrator\ERP.Orchestrator.csproj" />
    <ProjectReference Include="..\ERP.ProductModule.Application\ERP.ProductModule.Application.csproj" />
    <ProjectReference Include="..\ERP.ProductModule.Domain\ERP.ProductModule.Domain.csproj" />
    <ProjectReference Include="..\RabbitMQ\RabbitMQ.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\ProductContext\" />
  </ItemGroup>

</Project>
