<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="WolverineFx" Version="5.12.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ERP.Products.Application.Abstraction\ERP.Products.Application.Abstraction.csproj" />
      <ProjectReference Include="..\ERP.Products.Domain\ERP.Products.Domain.csproj" />
      <ProjectReference Include="..\ERP.Shared.Application.Abstractions\ERP.Shared.Application.Abstractions.csproj" />
      <ProjectReference Include="..\ERP.Shared.Kernel\ERP.Shared.Kernel.csproj" />
      <ProjectReference Include="..\ERP.Shared.Query.Contracts\ERP.Shared.Query.Contracts.csproj" />
    </ItemGroup>

</Project>
