<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <ItemGroup>
        <!-- Core EF package (IMPORTANT for ExecuteUpdateAsync / builders) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />

        <!-- Identity integration -->
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.1" />

        <!-- PostgreSQL provider -->

        <!-- EF Core tooling (design-time only) -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ERP.SharedKernal\ERP.SharedKernal.csproj" />
    </ItemGroup>

</Project>
