<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Photino.NET" Version="3.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RepoArchitect.Core\RepoArchitect.Core.csproj" />
    <ProjectReference Include="..\RepoArchitect.UI\RepoArchitect.UI.csproj" />
  </ItemGroup>
</Project>
