<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.0.0" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\ERP.Products.Messaging.RabbitMQ\ERP.Products.Messaging.RabbitMQ.csproj" />
    <ProjectReference Include="..\ERP.Orchestrator.Contract\ERP.Orchestrator.Contract.csproj" />
  </ItemGroup>

</Project>
