<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Mappers\**" />
    <EmbeddedResource Remove="Mappers\**" />
    <None Remove="Mappers\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WolverineFx" Version="5.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.Products.Application.Abstraction\ERP.Products.Application.Abstraction.csproj" />
    <ProjectReference Include="..\ERP.Products.Domain\ERP.Products.Domain.csproj" />  
    <ProjectReference Include="..\ERP.Shared.Command.Contracts\ERP.Shared.Command.Contracts.csproj" />
  </ItemGroup>
</Project>
