<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FastEndpoints" Version="7.2.0" />
    <PackageReference Include="FastEndpoints.Swagger" Version="7.2.0" />
    <PackageReference Include="WolverineFx" Version="5.12.0" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\ERP.Shared.Command.Contracts\ERP.Shared.Command.Contracts.csproj" />
    <ProjectReference Include="..\ERP.Shared.Kernel\ERP.Shared.Kernel.csproj" />
    <ProjectReference Include="..\ERP.Shared.Presentation\ERP.Shared.Presentation.csproj" />
  </ItemGroup>

</Project>
