<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.1">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
    </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ERP.InMemorySagaOrchestrator\ERP.InMemorySagaOrchestrator.csproj" />
      
    <ProjectReference Include="..\ERP.Products.Application\ERP.Products.Application.csproj" />
      
    <ProjectReference Include="..\ERP.Products.CommandApi\ERP.Products.CommandApi.csproj" />
    <ProjectReference Include="..\ERP.Products.CommandHandlers\ERP.Products.CommandHandlers.csproj" />
    <ProjectReference Include="..\ERP.Products.EventHandler\ERP.Products.EventHandler.csproj" />
      
    <ProjectReference Include="..\ERP.Products.JobSchedule.Hangfire\ERP.Products.JobSchedule.Hangfire.csproj" />
    <ProjectReference Include="..\ERP.Products.Messaging.InMemory\ERP.Products.Messaging.InMemory.csproj" />
    <ProjectReference Include="..\ERP.Products.Persistance.PgSQL\ERP.Products.Persistance.PgSQL.csproj" />
      
    <ProjectReference Include="..\ERP.Products.QueryApi\ERP.Products.QueryApi.csproj" />
    <ProjectReference Include="..\ERP.Products.QueryHandler\ERP.Products.QueryHandler.csproj" />
  </ItemGroup>

</Project>
